#!/usr/bin/env python3
"""Build a Font Awesome subset containing only the glyphs referenced in
src/components/icons.tsx.

Reads vendor/fontawesome (full Font Awesome Free distribution),
writes:
  src/app/fa-subset.css              - base FA rules + used glyph rules
  public/fonts/fa-solid-900.woff2    - subset font
  public/fonts/fa-regular-400.woff2  - subset font

Re-run whenever a new icon is added to icons.tsx:
  python3 scripts/build-fa-subset.py   (requires: pip install fonttools brotli)
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = ROOT / "src" / "components" / "icons.tsx"
FA_CSS = ROOT / "vendor" / "fontawesome" / "css" / "all.min.css"
FA_FONTS = ROOT / "vendor" / "fontawesome" / "webfonts"
OUT_CSS = ROOT / "src" / "app" / "fa-subset.css"
OUT_FONTS = ROOT / "public" / "fonts"

src = ICONS.read_text()
used = sorted(set(re.findall(r'fa-(?:solid|regular) (fa-[a-z0-9-]+)', src)))
if not used:
    sys.exit("no icons found")

css = FA_CSS.read_text()
css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)

# Glyph rules: `.fa-name{--fa:"\f015"}` (possibly several selectors). Keep only used ones.
glyphs: list[str] = []
codepoints: set[str] = set()

def _glyph(m: re.Match[str]) -> str:
    sel, body = m.group(1), m.group(2)
    names = [n.strip().lstrip(".") for n in sel.split(",")]
    if any(n in used for n in names):
        glyphs.append(f"{sel}{{{body}}}")
        codepoints.update(re.findall(r'--fa:"\\([0-9a-f]+)"', body))
    return ""

base_css = re.sub(r'((?:\.fa-[a-z0-9-]+,?)+)\{(--fa:"\\[0-9a-f]+"[^{}]*)\}', _glyph, css)
# Drop all shipped @font-face rules; we add our own pointing at the subset fonts.
base_css = re.sub(r'@font-face\{[^{}]*\}', '', base_css)
base = [base_css.strip()]

font_faces = (
    '@font-face{font-family:"Font Awesome 7 Free";font-style:normal;font-weight:400;'
    'font-display:block;src:url(/fonts/fa-regular-400.woff2) format("woff2")}'
    '@font-face{font-family:"Font Awesome 7 Free";font-style:normal;font-weight:900;'
    'font-display:block;src:url(/fonts/fa-solid-900.woff2) format("woff2")}'
)
header = (
    "/* Font Awesome Free 7 subset — generated by scripts/build-fa-subset.py; "
    "do not edit by hand. License: https://fontawesome.com/license/free */\n"
)
OUT_CSS.write_text(header + font_faces + "".join(base) + "".join(glyphs) + "\n")

OUT_FONTS.mkdir(exist_ok=True)
unicodes = ",".join(f"U+{cp}" for cp in sorted(codepoints))
for name in ("fa-solid-900", "fa-regular-400"):
    subprocess.run(
        [
            sys.executable, "-m", "fontTools.subset",
            str(FA_FONTS / f"{name}.woff2"),
            f"--unicodes={unicodes}",
            "--flavor=woff2",
            "--no-hinting",
            "--desubroutinize",
            f"--output-file={OUT_FONTS / name}.woff2",
        ],
        check=True,
    )
print(f"{len(used)} icons, {len(codepoints)} codepoints, {len(base)} base rules, {len(glyphs)} glyph rules")
