-- Defense-in-depth, found while checking the new insurance tables' grants:
-- Supabase's default privileges for schema public — this is their
-- documented, intended architecture, not a misconfiguration — grant ALL
-- (insert/update/delete/select/...) on every new table to anon and
-- authenticated at creation time. The model is that RLS is the real gate
-- and the underlying grant is meant to be broad; that holds here (RLS is
-- enabled with a real policy on all 32+ tables, verified separately), but
-- it means wallets, transactions, and wallet_ledger — the actual balance
-- and money-movement tables — all currently carry raw INSERT/UPDATE/DELETE
-- grants to anon sitting underneath their RLS policies. Every legitimate
-- write already goes through a SECURITY DEFINER function (which runs as
-- its owner and isn't subject to these grants at all), so nothing
-- currently depends on anon/authenticated having them — but leaving them
-- in place means RLS is the ONLY thing standing between anon and a raw
-- write to wallets, with no second layer if RLS were ever accidentally
-- disabled or a future policy shipped with a subtle bug.
--
-- Every statement below was generated by cross-referencing each table's
-- actual grants against pg_policies: only a (table, role, command) triple
-- where NO existing policy could ever apply to that combination is
-- revoked. That makes this behavior-neutral by construction — anything a
-- real policy relies on (e.g. guest_checkout_intents' public INSERT,
-- profiles' own-row UPDATE, messages' own INSERT) is left untouched.
--
-- Deliberately not touching the schema-wide default privileges
-- themselves (ALTER DEFAULT PRIVILEGES) — that's Supabase's documented
-- model, other tooling (the Studio table editor, future migrations)
-- assumes it, and RLS is already comprehensive. This migration cleans up
-- the current, known state; it doesn't change what a table gets when
-- it's created next — the same check should be re-run after adding any
-- table intended to be RPC-only, the same way it was for insurance_*
-- here.
revoke DELETE, INSERT, UPDATE on table public.admin_audit_log from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.api_modules_safe from anon, authenticated;
revoke DELETE, INSERT on table public.conversations from anon, authenticated;
revoke DELETE, UPDATE on table public.dispute_messages from anon, authenticated;
revoke DELETE on table public.disputes from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.gift_vouchers from anon, authenticated;
revoke DELETE, UPDATE on table public.guest_checkout_intents from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.insurance_clients from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.insurance_policies from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.insurance_premium_payments from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.integration_health from anon, authenticated;
revoke DELETE, UPDATE on table public.messages from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.p2p_transfers from anon, authenticated;
revoke DELETE, INSERT on table public.profiles from anon, authenticated;
revoke DELETE, UPDATE on table public.support_ticket_messages from anon, authenticated;
revoke DELETE on table public.support_tickets from anon, authenticated;
revoke DELETE, UPDATE on table public.topup_intents from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.transaction_events from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.transactions from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.wallet_ledger from anon, authenticated;
revoke DELETE, INSERT, UPDATE on table public.wallets from anon, authenticated;
